name: hotelhub
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  sqflite: ^2.3.2
  path_provider: ^2.0.2
  animated_notch_bottom_bar: ^1.0.0
  get: ^4.6.1
  provider: ^6.1.2
  reactive_theme: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  firebase_auth: ^4.16.0
  firebase_core: ^2.20.0
  cloud_firestore: ^4.14.0
  http: ^1.1.0
  dio: ^5.4.3+1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hotel_1.jpg
    - assets/images/hotel_2.jpg
    - assets/images/hotel_3.png
    - assets/images/hotel_4.jpg
    - assets/images/hotel_5.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
